### ISSUE TITLE
Windows and rsync - deploy issues.

### ISSUE THREAD

**Issue by teebu** [RebelMail/node-lambda#13]
I was trying to get your node-lambda to work, but I am having issues with rsync on my windows machine. 

It's not using cygdrive and pathing's are not working.

I'm using git bash. I changed the code to, I realize it's missing the exclude features:

````
exec('cp -r . ' + codeDirectory, function(err, stdout, stderr) {
`````

**Comment by motdotla** [comment]
Did changing the code to that internally, fix it up for you?

**Comment by teebu** [comment]
That fixed it for me. 

````
Lambda.prototype._rsync = function(program, codeDirectory, callback) {
  //exec('rsync -r --exclude=.git --exclude=*.log --exclude=node_modules . ' + codeDirectory, function(err, stdout, stderr) {
  exec('cp -r . ' + codeDirectory, function(err, stdout, stderr) {
    if (err) {
      throw err;
    }

    return callback(null, true);
  });
};
````

**Comment by motdotla** [comment]
Ah, ouch. Yeah that is not excluding anything. That will wrap up all of your `.git`, `*.log`, and `node_modules` - not desired behavior.

**Comment by motdotla** [comment]
For rsync that will have to be fixed on your end. 

For the pathing issues I'm closing this issue and moving that conversation to here: https://github.com/RebelMail/node-lambda/issues/14
