### ISSUE TITLE
Zip isn't working on windows

### ISSUE THREAD

**Issue by teebu** [RebelMail/node-lambda#14]
Using git bash. The node-deploy generates some zip (maybe? I can't find the file) but it seems that it's not working.

I'm guessing its because of the paths again. ie

````
C:/Users/myusername/AppData/Local/Temp/testfunction-1429006026284/node_modules\async\component.json
````

Update: 
I created a temp zip to see what's inside, seems like it maybe working. node-lambda uploading and also manually uploading that zip procudes the same result. A no-working lambda function.

I created the temp zip using Lambda.prototype._zip = function
````
  fs.writeFileSync('c:/temp/test.zip', data, 'binary');
  return callback(null, 'c:/temp/test.zip');
````
Update 2:
I'm getting "Service error." from Lambda when trying to invoke this function with the generated zip.

**Comment by teebu** [comment]
Zipping up the files by hand and uploading manually works.

**Comment by motdotla** [comment]
Can you speak more to the pathing problem you are having? I'm not very familiar with windows. Describe it as detailed as possible.

This uses node-zip under the hood which seems to have windows support [1]

[1] https://github.com/daraosn/node-zip/pull/11

**Comment by teebu** [comment]
Regarding Zip. I can see it's actually zipping the file with my modification of your code. but maybe the method it's using to zip, Amazon is not happy with it and not recognizing it. I haven't done much to debug that situation. 

Regarding pathing and rsync:
When copying files from one drive to another using rsync it expects something like '/drive/path/' but it's getting 'c:\something\path/temp/app-123123' On windows and it throws errors, you would need '/cygdrive/c/path/temp/app-123123'

https://cygwin.com/cygwin-ug-net/using.html#cygdrive

**Comment by teebu** [comment]
I'd like to suggest to use built in libariries to copy files, like fs or use https://github.com/jprichardson/node-fs-extra to be less reliant on 3rd party programs like rsync.

**Comment by teebu** [comment]
Just an update on my progress. I tried a few zip modules, yazm had potentials, the zips it created actually ran on Amazon's lambda tests, but i started to run into path problems in it as well when the folder structure got more complex. Search continues on a working zip module. 

The copy module that works for me right now is ncp. It has a built in filter option, which is good. 

```
  ncp.limit = 16;
  var options = { filter : /^((?!\.idea|.git|.env|node_modules|^(.*?)\.log).)*$/i }; // filter out files

  ncp(process.cwd(), codeDirectory, options, function (err) {
    if (err) {
      console.error(err);
      return callback(err)
    }
```

**Comment by teebu** [comment]
I also ended up using 7zip to zip up the file.

**Comment by motdotla** [comment]
Thank you for all the info @teebu. I'm going to close this, but will re-open if others express interest. I can't make the time at the moment to support these Windows issues. I apologize for that. Possibly some time in the future.
