### ISSUE TITLE
Deploy options commands overlap "-m"

### ISSUE THREAD

**Issue by teebu** [RebelMail/node-lambda#16]
The deploy -m command overlaps 2 settings. --memorySize works, -m updates mode. 

-m, --mode [event]                Lambda Mode
-o, --role [your_role]            Amazon Role ARN
-m, --memorySize [128]            Lambda Memory Size

**Comment by teebu** [comment]
Options.

**Comment by motdotla** [comment]
Thanks for catching this :dancer: 

Fixed here: https://github.com/RebelMail/node-lambda/pull/17

Use latest version `0.5.0`.
