### ISSUE TITLE
Amazon changed the uploadFunction it's now 3 new functions.

### ISSUE THREAD

**Issue by teebu** [RebelMail/node-lambda#18]
[http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html)

Looks like uploadFunction is removed in the current API. 

createFunction -> Creates a new Lambda function. If the function name already exists, the operation will fail. 
updateFunctionCode -> Updates the code for the specified Lambda function.
updateFunctionConfiguration -> Updates the configuration parameters 

Just a note, your code is still working using the old API, for now.

**Comment by motdotla** [comment]
Ok, thanks for the heads up. 

Line is here - https://github.com/RebelMail/node-lambda/blob/master/lib/main.js#L168 - and I imagine will be supported into the future for a while.

Welcome pull requests to update, but until then we will leave as is.
