### ISSUE TITLE
Generated zip file omits Unix file permissions - breaks Lambda functions with binaries

### ISSUE THREAD

**Issue by christianklotz** [RebelMail/node-lambda#19]
If you include a binary file in the package which is meant to be called by the Lambda function it will fail executing the binary as the file permissions are not preserved in the zip.

Lambda will raise the following error message:
```json
{
  "errorMessage": "Process exited before completing request"
}
```

This is caused by the following error when calling `execFile` using the `child_process` package.
```log
[Error: spawn EACCES] code: 'EACCES', errno: 'EACCES', syscall: 'spawn'
```

I've tried including the `platform` in the zip options as follows but it doesn't work:
```js
var options = {
    type: 'nodebuffer',
    compression: 'DEFLATE',
    platform: process.platform
  }
```

The only solution I've come up with so far is using the native zip command. I'm aware that this will work on Unix machines but breaks on Windows. Maybe the following method should only be used on Unix machines based on `process.platform`?

```js
Lambda.prototype._nativeZip = function(program, codeDirectory, callback) {
  var zipfile = this._zipfileTmpPath(program)
    , cmd = 'zip -r ' + zipfile + ' .'
    , run = exec(cmd, { cwd: codeDirectory }, function (err, stdout, stderr) {
        if (err !== null) {
          callback(err, null)
          return
        }

        var data = fs.readFileSync(zipfile)
        callback(null, data)
    })
}
```

**Comment by motdotla** [comment]
Hey @christianklotz can you confirm this is still occurring for you on `0.6.0` version?

**Comment by motdotla** [comment]
This is older now. Closing. I'll re-open if still a problem.

**Comment by christianklotz** [comment]
I can confirm `0.6.0` works. Thanks for accepting the PR.
