### ISSUE TITLE
depoy.env use

### ISSUE THREAD

**Issue by debajyotimahanta** [RebelMail/node-lambda#27]
the deploy.env is not wokring, i added variables there but i am not able to retrive it using process.env. If its a part of .env it works locally

**Comment by motdotla** [comment]
I see. It occurs using `configFile` flag here: https://github.com/RebelMail/node-lambda#deploy

I will update the README to remove the deploy.env file confusion. It could be any configFile passed to it.

**Comment by motdotla** [comment]
Updated here @debajyotimahanta: https://github.com/RebelMail/node-lambda/commit/aad9d23c4bf2a7b927bbdbb15d2bfa643bc677f1

**Comment by debajyotimahanta** [comment]
Thanks now I get it. I did see the test case and it makes more sense.
Wondering if there is way to exclude test cases
