### ISSUE TITLE
Clean modules and run npm install --production

### ISSUE THREAD

**Issue by elbuo8** [RebelMail/node-lambda#4]
This avoids the footprint that devDependencies bring in.

**Comment by motdotla** [comment]
this will be excellent, and really save us a big problem in the future (by eliminating that human error to forget to run npm install)

I think this is important to have sooner than later.

**Comment by elbuo8** [comment]
:+1:

**Comment by elbuo8** [comment]
https://github.com/RebelMail/node-lambda/pull/5 

Now we have it.
