### ISSUE TITLE
Rename AWS_ROLE ENV variable

### ISSUE THREAD

**Issue by hanchang** [RebelMail/node-lambda#8]
The `AWS_ROLE` variable in the `.env` file is somewhat misleading, since it actually represents the Role ARN. As a result, it may be a good idea to rename it to AWS_ROLE_ARN for clarity so others in the future don't get an error message:

    { [ValidationException: 1 validation error detected: Value 'worker' at 'role' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:aws:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+]
      message: '1 validation error detected: Value \'worker\' at \'role\' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:aws:iam::\\d{12}:role/?[a-zA-Z_0-9+=,.@\\-_/]+',
      code: 'ValidationException',
      time: Sun Feb 15 2015 21:18:18 GMT-0500 (EST),
      statusCode: 400,
      retryable: false,
      retryDelay: 30 }

That said, the error message was excellent, very descriptive!

**Comment by motdotla** [comment]
If we get some :+1: s on this, then we'll consider that.

**Comment by jamesyoung** [comment]
:+1:

**Comment by elbuo8** [comment]
:+1:

**Comment by motdotla** [comment]
This is updated in `0.3.15` and up on npm. Allows for either `AWS_ROLE_ARN` or `AWS_ROLE`.

FYI: that error comes directly from Amazon and passed back to the library - so that error message will always say 'role' until/if they update their error message.
